version: '3'

services:
  app:
    build:
      args:
        user: crater-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: crater-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - crater

  db:
    image: mariadb
    restart: always
    volumes:
      - ./docker-compose/db/data:/var/lib/mysql:rw,delegated
    environment:
      MYSQL_USER: admin_atlantida_code
      MYSQL_PASSWORD: "3SX24B84LP@PfGv*3xKE*F#d865Ui8HYmrLxLzEV"
      MYSQL_DATABASE: admin_atlantida_code
      MYSQL_ROOT_PASSWORD: "3SX24B84LP@PfGv*3xKE*F#d865Ui8HYmrLxLzEV"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - crater

  cron:
    build:
      context: ./
      dockerfile: ./docker-compose/cron.dockerfile
    volumes:
      - ./:/var/www
    networks:
      - crater

  cache:
    restart: always
    image: redis:alpine
    volumes:
      - ./docker-compose/cache/data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
      - --requirepass ${REDIS_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '512M'
    networks:
      - crater

networks:
  crater:
    driver: bridge
